// File generated by FlutterFire CLI — NOT YET CONFIGURED.
//
// This is a placeholder. Run `flutterfire configure` from the project
// root after creating your Firebase project; it will overwrite this
// file with your real project's options. Until then, Firebase
// initialization will fail gracefully and the app runs offline-only
// (see main.dart).
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate real options.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'NOT_CONFIGURED',
    appId: 'NOT_CONFIGURED',
    messagingSenderId: 'NOT_CONFIGURED',
    projectId: 'NOT_CONFIGURED',
  );

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyBTtP6G7gRJBk6zaZblII8Wa6ipEZSrS80',
    appId: '1:639863042901:android:a230b3676cfed2cf0635dc',
    messagingSenderId: '639863042901',
    projectId: 'schedul-6e64a',
    storageBucket: 'schedul-6e64a.firebasestorage.app',
  );

  static const ios = FirebaseOptions(
    apiKey: 'NOT_CONFIGURED',
    appId: 'NOT_CONFIGURED',
    messagingSenderId: 'NOT_CONFIGURED',
    projectId: 'NOT_CONFIGURED',
    iosBundleId: 'com.example.rivermouthScheduler',
  );
}
